name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Deps
      run: |
        sudo apt-get install ocl-icd-opencl-dev libhwloc-dev
        git submodule update --init
        ./extern/filecoin-ffi/install-filcrypto

    - name: Build
      env:
        GOPROXY: "https://goproxy.io,direct"
        GO111MODULE: "on"
      run: go build

    - name: Test
      run: go test -v ./...
